export const filter = {
  category: [
    { name: "All", value: "all" },
    { name: "T-Shirts", value: "shirts" },
    { name: "Shirts", value: "shirts" },
    { name: "Dresses", value: "dresses" },
    { name: "Skirts", value: "skirts" },
    { name: "Pants", value: "pants" },
    { name: "Jackets", value: "jackets" },
    { name: "Hats", value: "hats" },
    { name: "Shoes", value: "shoes" },
    { name: "Accessories", value: "accessories" },
  ],
  Gender: [
    { name: "All", value: "all" },
    { name: "Men", value: "men" },
    { name: "Women", value: "women" },
    { name: "Kids", value: "kids" },
  ],
  Price: [
    { name: "All", value: "all" },
    { name: "Under $25", value: "0-25" },
    { name: "$25 to $50", value: "25-50" },
    { name: "$50 to $100", value: "50-100" },
    { name: "Over $100", value: "100-10000" },
  ],
  Size: [
    { name: "All", value: "all" },
    { name: "XS", value: "xs" },
    { name: "S", value: "s" },
    { name: "M", value: "m" },
    { name: "L", value: "l" },
    { name: "XL", value: "xl" },
    { name: "XXL", value: "xxl" },
  ],
  Color: [
    { name: "All", value: "all" },
    { name: "Black", value: "black" },
    { name: "White", value: "white" },
    { name: "Red", value: "red" },
    { name: "Blue", value: "blue" },
    { name: "Green", value: "green" },
    { name: "Yellow", value: "yellow" },
    { name: "Orange", value: "orange" },
    { name: "Purple", value: "purple" },
    { name: "Pink", value: "pink" },
    { name: "Brown", value: "brown" },
    { name: "Grey", value: "grey" },
    { name: "Beige", value: "beige" },
    { name: "Gold", value: "gold" },
    { name: "Silver", value: "silver" },
    { name: "Multicolor", value: "multicolor" },
  ],
};
