// Temporary mock/fallback data so the home page can be visualized fully
// populated without a reachable Supabase instance. Not for production use —
// remove once no longer needed for visualization.

import { Brand } from "@/types/system-types/Brand";
import { Collection } from "@/types/system-types/Collection";
import { Product } from "@/types/system-types/Product";
import { Event } from "@/types/system-types/Event";
import { Article } from "@/types/system-types/Article";

export const MOCK_BRANDS: Brand[] = [
  {
    id: "4a511eee-68ab-45cd-b7d2-2a2a1759904b",
    name: "Adaeze Atelier",
    description:
      "A Lagos-based atelier blending hand-dyed Ankara prints with tailored, contemporary silhouettes.",
    contact: "+234 800 000 0001",
    email: "hello@adaezeatelier.com",
    location: "Lagos, Nigeria",
    profile_picture: "/Pages/Home/brand-story/variant-3-c.jpg",
    banner_image: "/Pages/Home/brand-story/variant-3-a.jpg",
    status: "approved",
    supabase_user_id: "00000000-0000-0000-0000-000000000001",
    created_at: null,
    updated_at: null,
    url: null,
    commission_rate: 0,
    payout_account_name: null,
    payout_account_number: null,
    payout_bank_code: null,
    payout_verified: false,
    paystack_subaccount_code: null,
  },
  {
    id: "687117e8-e645-4d06-b850-ec1757e3bd50",
    name: "Kente & Co.",
    description:
      "Modernizing heritage kente weaves into everyday accessories and ready-to-wear pieces.",
    contact: "+233 800 000 0002",
    email: "hello@kenteandco.com",
    location: "Accra, Ghana",
    profile_picture: "/Pages/Home/brand-story/variant-1-b.jpg",
    banner_image: "/Pages/Home/brand-story/variant-1-a.jpg",
    status: "approved",
    supabase_user_id: "00000000-0000-0000-0000-000000000002",
    created_at: null,
    updated_at: null,
    url: null,
    commission_rate: 0,
    payout_account_name: null,
    payout_account_number: null,
    payout_bank_code: null,
    payout_verified: false,
    paystack_subaccount_code: null,
  },
  {
    id: "bb1323cd-b9c4-461f-831c-28f2818274da",
    name: "Sable Row",
    description:
      "Minimalist tailoring in natural fibers, sourced and sewn entirely on the continent.",
    contact: "+27 800 000 0003",
    email: "hello@sablerow.com",
    location: "Cape Town, South Africa",
    profile_picture: "/Pages/Home/brand-story/variant-3-b.jpg",
    banner_image: "/Pages/Home/brand-story/variant-3-a.jpg",
    status: "approved",
    supabase_user_id: "00000000-0000-0000-0000-000000000003",
    created_at: null,
    updated_at: null,
    url: null,
    commission_rate: 0,
    payout_account_name: null,
    payout_account_number: null,
    payout_bank_code: null,
    payout_verified: false,
    paystack_subaccount_code: null,
  },
  {
    id: "e2434813-c053-448d-be24-57aad065d1c8",
    name: "Nomad Thread Studio",
    description:
      "Handmade jewelry and accessories made in small batches with reclaimed brass and stone.",
    contact: "+254 800 000 0004",
    email: "hello@nomadthreadstudio.com",
    location: "Nairobi, Kenya",
    profile_picture: "/Pages/Home/brand-story/variant-4-a.jpg",
    banner_image: "/Pages/Home/brand-story/variant-4-b.jpg",
    status: "approved",
    supabase_user_id: "00000000-0000-0000-0000-000000000004",
    created_at: null,
    updated_at: null,
    url: null,
    commission_rate: 0,
    payout_account_name: null,
    payout_account_number: null,
    payout_bank_code: null,
    payout_verified: false,
    paystack_subaccount_code: null,
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "46173dd7-b1ea-41b5-83ae-74de7312fcc6",
    brand_id: MOCK_BRANDS[0].id,
    name: "Desert Bloom",
    slug: "desert-bloom",
    category: "Womenswear",
    category_id: null,
    description: "Sun-warmed tones and flowing silhouettes for the dry season.",
    display_image: "/Pages/Collections/collection.webp",
    created_at: null,
    updated_at: null,
  },
  {
    id: "65d54871-5cf7-498a-a941-d46216f96bd8",
    brand_id: MOCK_BRANDS[1].id,
    name: "Lagos Nights",
    slug: "lagos-nights",
    category: "Eveningwear",
    category_id: null,
    description: "Bold prints and statement fabrics built for the dance floor.",
    display_image: "/Pages/Collections/collection2.png",
    created_at: null,
    updated_at: null,
  },
  {
    id: "f09aef16-e5eb-4662-aa4f-38e637fbee1e",
    brand_id: MOCK_BRANDS[2].id,
    name: "Coastal Drift",
    slug: "coastal-drift",
    category: "Resortwear",
    category_id: null,
    description:
      "Breathable linens and relaxed tailoring inspired by the Cape coast.",
    display_image: "/Pages/Collections/collection4.webp",
    created_at: null,
    updated_at: null,
  },
  {
    id: "4ac17eea-e0f8-42df-b88f-ce4f8b50b9f4",
    brand_id: MOCK_BRANDS[3].id,
    name: "Heritage Weave",
    slug: "heritage-weave",
    category: "Accessories",
    category_id: null,
    description:
      "Handmade jewelry that carries traditional craft into daily wear.",
    display_image: "/Pages/Collections/collection6.jpg",
    created_at: null,
    updated_at: null,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "e1614c04-8332-47e9-b9c7-158a71a6ea4a",
    brand_id: MOCK_BRANDS[0].id,
    collection_id: MOCK_COLLECTIONS[0].id,
    name: "Ankara Wrap Dress",
    slug: "ankara-wrap-dress",
    description: "A hand-dyed Ankara wrap dress with an adjustable waist tie.",
    price: 89,
    category_id: 1,
    features: ["Hand-dyed fabric", "Adjustable fit", "Machine washable"],
    product_images: ["/Pages/Home/brand-story/variant-1-c.jpg"],
    rating: 4.8,
    return_days: 30,
    reviews_count: 42,
    specifications: {},
    stock_quantity: 18,
    warranty_years: null,
    free_shipping: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: "c056591f-f84e-4a6a-895e-5520d4cb56d6",
    brand_id: MOCK_BRANDS[1].id,
    collection_id: MOCK_COLLECTIONS[1].id,
    name: "Handwoven Kente Scarf",
    slug: "handwoven-kente-scarf",
    description: "A traditionally handwoven kente scarf in a modern colorway.",
    price: 65,
    category_id: 2,
    features: ["100% cotton", "Handwoven", "One size"],
    product_images: ["/Pages/Home/brand-story/variant-2-c.jpg"],
    rating: 4.9,
    return_days: 30,
    reviews_count: 27,
    specifications: {},
    stock_quantity: 24,
    warranty_years: null,
    free_shipping: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: "1212b38e-dd22-4f4e-9753-6c67239b179d",
    brand_id: MOCK_BRANDS[3].id,
    collection_id: MOCK_COLLECTIONS[3].id,
    name: "Beaded Statement Necklace",
    slug: "beaded-statement-necklace",
    description:
      "A layered brass and stone necklace, handmade in small batches.",
    price: 54,
    category_id: 3,
    features: ["Reclaimed brass", "Adjustable clasp"],
    product_images: ["/Pages/Home/brand-story/variant-4-b.jpg"],
    rating: 4.7,
    return_days: 14,
    reviews_count: 15,
    specifications: {},
    stock_quantity: 9,
    warranty_years: null,
    free_shipping: false,
    created_at: null,
    updated_at: null,
  },
  {
    id: "7202e767-7cc0-4c03-95c9-a1bd2f3f17b8",
    brand_id: MOCK_BRANDS[2].id,
    collection_id: MOCK_COLLECTIONS[2].id,
    name: "Linen Tailored Blazer",
    slug: "linen-tailored-blazer",
    description: "A relaxed-fit linen blazer, cut for warm-weather tailoring.",
    price: 145,
    category_id: 1,
    features: ["100% linen", "Fully lined", "Dry clean only"],
    product_images: ["/Pages/Home/brand-story/variant-3-a.jpg"],
    rating: 4.6,
    return_days: 30,
    reviews_count: 33,
    specifications: {},
    stock_quantity: 11,
    warranty_years: null,
    free_shipping: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: "077d2b55-c28a-4783-b217-5f35a2d617a3",
    brand_id: MOCK_BRANDS[2].id,
    collection_id: MOCK_COLLECTIONS[2].id,
    name: "Leather Woven Sandals",
    slug: "leather-woven-sandals",
    description: "Hand-woven leather sandals, made to order.",
    price: 78,
    category_id: 4,
    features: ["Genuine leather", "Made to order"],
    product_images: ["/Pages/Home/brand-story/variant-1-a.jpg"],
    rating: 4.5,
    return_days: 14,
    reviews_count: 8,
    specifications: {},
    stock_quantity: 6,
    warranty_years: null,
    free_shipping: false,
    created_at: null,
    updated_at: null,
  },
  {
    id: "dae2b0f7-6499-4b88-8f5e-bb9c56d0e648",
    brand_id: MOCK_BRANDS[0].id,
    collection_id: MOCK_COLLECTIONS[0].id,
    name: "Silk Head Wrap",
    slug: "silk-head-wrap",
    description: "A printed silk head wrap, finished with hand-rolled hems.",
    price: 38,
    category_id: 3,
    features: ["100% silk", "Hand-rolled hem"],
    product_images: ["/Pages/Home/brand-story/variant-2-a.jpg"],
    rating: 4.9,
    return_days: 30,
    reviews_count: 51,
    specifications: {},
    stock_quantity: 30,
    warranty_years: null,
    free_shipping: true,
    created_at: null,
    updated_at: null,
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: "f38697c3-3871-4e22-b467-d3d998c5b8f5",
    brand_id: MOCK_BRANDS[0].id,
    title: "Lagos Fashion Week Preview",
    slug: "lagos-fashion-week-preview",
    description:
      "An early look at the collections walking this season's runway.",
    display_image: "/Pages/Home/events.jpg",
    start_date: "2026-08-20T18:00:00.000Z",
    end_date: "2026-08-20T21:00:00.000Z",
    location: "Lagos, Nigeria",
    is_virtual: false,
    admission_price: 25,
    capacity: 200,
    duration_hours: 3,
    exhibitor_count: 12,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "first-come",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "05280ed9-1e44-4877-97ba-e5155e0db1b5",
    brand_id: MOCK_BRANDS[0].id,
    title: "Trunk Show: Adaeze Atelier",
    slug: "trunk-show-adaeze-atelier",
    description: "Preview and shop the new Desert Bloom collection in person.",
    display_image: "/Pages/Home/brand-story/variant-1-c.jpg",
    start_date: "2026-08-27T16:00:00.000Z",
    end_date: "2026-08-27T19:00:00.000Z",
    location: "Lagos, Nigeria",
    is_virtual: false,
    admission_price: 0,
    capacity: 60,
    duration_hours: 3,
    exhibitor_count: 1,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "rsvp",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "102b85f2-4a33-41e6-ac76-9a078e638214",
    brand_id: MOCK_BRANDS[2].id,
    title: "Pop-Up: Sable Row",
    slug: "pop-up-sable-row",
    description:
      "A weekend pop-up shop featuring the full Coastal Drift collection.",
    display_image: "/Pages/Home/brand-story/variant-3-a.jpg",
    start_date: "2026-09-05T10:00:00.000Z",
    end_date: "2026-09-06T18:00:00.000Z",
    location: "Cape Town, South Africa",
    is_virtual: false,
    admission_price: 0,
    capacity: 150,
    duration_hours: 8,
    exhibitor_count: 1,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "walk-in",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "bb6a556b-efa5-408d-aeed-f9851da7d21a",
    brand_id: MOCK_BRANDS[1].id,
    title: "Designer Meet & Greet",
    slug: "designer-meet-and-greet",
    description: "Sit down with three of the platform's featured designers.",
    display_image: "/Pages/Home/brand-story/variant-1-b.jpg",
    start_date: "2026-09-12T17:00:00.000Z",
    end_date: "2026-09-12T19:30:00.000Z",
    location: "Accra, Ghana",
    is_virtual: false,
    admission_price: 15,
    capacity: 80,
    duration_hours: 2,
    exhibitor_count: 3,
    featured_speakers_description: "Three founders in conversation.",
    parking_available: false,
    registration_basis: "rsvp",
    speakers: "Adaeze, Kwame, Naledi",
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "12c32782-3f8a-4846-85ae-f1843a6e6e8f",
    brand_id: MOCK_BRANDS[3].id,
    title: "Textile & Craft Market",
    slug: "textile-and-craft-market",
    description:
      "A curated market of textile and jewelry makers from across the continent.",
    display_image: "/Pages/Home/brand-story/variant-2-b.jpg",
    start_date: "2026-09-19T09:00:00.000Z",
    end_date: "2026-09-19T17:00:00.000Z",
    location: "Nairobi, Kenya",
    is_virtual: false,
    admission_price: 5,
    capacity: 500,
    duration_hours: 8,
    exhibitor_count: 30,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "walk-in",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "07b673ad-52ce-4673-9b4a-2f0480aedb54",
    brand_id: MOCK_BRANDS[2].id,
    title: "Virtual Styling Workshop",
    slug: "virtual-styling-workshop",
    description:
      "A live, online session on building a season-proof capsule wardrobe.",
    display_image: "/Pages/Home/brand-story/variant-3-b.jpg",
    start_date: "2026-09-25T18:00:00.000Z",
    end_date: "2026-09-25T19:00:00.000Z",
    location: null,
    is_virtual: true,
    admission_price: 10,
    capacity: 300,
    duration_hours: 1,
    exhibitor_count: 1,
    featured_speakers_description: null,
    parking_available: false,
    registration_basis: "rsvp",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "cc7456da-5786-48c3-978c-97cd430aba69",
    brand_id: MOCK_BRANDS[1].id,
    title: "Kente & Co. Launch Party",
    slug: "kente-and-co-launch-party",
    description: "Celebrating the launch of the Lagos Nights collection.",
    display_image: "/Pages/Home/brand-story/variant-2-a.jpg",
    start_date: "2026-10-02T19:00:00.000Z",
    end_date: "2026-10-02T22:00:00.000Z",
    location: "Accra, Ghana",
    is_virtual: false,
    admission_price: 0,
    capacity: 120,
    duration_hours: 3,
    exhibitor_count: 1,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "rsvp",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
  {
    id: "712ec308-520e-4035-9076-371541883fb3",
    brand_id: MOCK_BRANDS[3].id,
    title: "Nomad Thread Studio Sample Sale",
    slug: "nomad-thread-studio-sample-sale",
    description:
      "One weekend only — samples and past-season pieces at a discount.",
    display_image: "/Pages/Home/brand-story/variant-4-c.jpg",
    start_date: "2026-10-10T10:00:00.000Z",
    end_date: "2026-10-11T16:00:00.000Z",
    location: "Nairobi, Kenya",
    is_virtual: false,
    admission_price: 0,
    capacity: 100,
    duration_hours: 6,
    exhibitor_count: 1,
    featured_speakers_description: null,
    parking_available: true,
    registration_basis: "walk-in",
    speakers: null,
    tickets_url: null,
    what_to_expect: [
      "Meet the designers",
      "Shop the latest pieces",
      "Light refreshments",
    ],
    created_at: null,
    updated_at: null,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: "c7b7edbc-0f0f-4a68-84a5-180b2e368694",
    brand_id: MOCK_BRANDS[0].id,
    title: "5 Brands Redefining African Streetwear",
    slug: "5-brands-redefining-african-streetwear",
    description:
      "A look at the labels blending heritage textiles with street silhouettes.",
    content: "",
    display_image: "/Pages/Home/news.jpg",
    author: "Amaka Obi",
    author_bio: null,
    reading_time_minutes: 5,
    tags: ["streetwear", "trends"],
    created_at: "2026-08-05T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "d1e3c381-098f-46a8-bc6e-6642a1ead4ae",
    brand_id: MOCK_BRANDS[1].id,
    title: "Inside Lagos's Rising Fashion Scene",
    slug: "inside-lagos-rising-fashion-scene",
    description:
      "How a new generation of designers is building for a global audience.",
    content: "",
    display_image: "/Pages/Home/brand-story/variant-1-b.jpg",
    author: "Tunde Bakare",
    author_bio: null,
    reading_time_minutes: 7,
    tags: ["lagos", "designers"],
    created_at: "2026-08-03T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "eeba46de-2947-4d2f-af0d-63427e27e90d",
    brand_id: MOCK_BRANDS[2].id,
    title: "How Sable Row Sources Its Fabrics",
    slug: "how-sable-row-sources-its-fabrics",
    description: "A behind-the-scenes look at sourcing linen from local mills.",
    content: "",
    display_image: "/Pages/Home/brand-story/variant-2-c.jpg",
    author: "Naledi Khumalo",
    author_bio: null,
    reading_time_minutes: 4,
    tags: ["sourcing", "sustainability"],
    created_at: "2026-07-30T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "12831660-0ef7-4328-ae23-7b2fcecb7af0",
    brand_id: MOCK_BRANDS[3].id,
    title: "The Return of Statement Jewelry",
    slug: "the-return-of-statement-jewelry",
    description: "Why bold, handmade pieces are back at the center of styling.",
    content: "",
    display_image: "/Pages/Home/brand-story/variant-4-b.jpg",
    author: "Wanjiru Kamau",
    author_bio: null,
    reading_time_minutes: 3,
    tags: ["jewelry", "accessories"],
    created_at: "2026-07-28T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "ac985fe2-2d9c-4109-a31d-1eee44454244",
    brand_id: MOCK_BRANDS[0].id,
    title: "Meet the Designer: Adaeze Atelier",
    slug: "meet-the-designer-adaeze-atelier",
    description: "The story behind the atelier's hand-dyed Ankara techniques.",
    content: "",
    display_image: "/Pages/Home/brand-story/variant-1-a.jpg",
    author: "Amaka Obi",
    author_bio: null,
    reading_time_minutes: 6,
    tags: ["profile", "designers"],
    created_at: "2026-07-25T09:00:00.000Z",
    updated_at: null,
  },
];
