/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 standingIdle.glb 
*/

import React from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Models/standingIdle.glb");
  return (
    <Canvas suppressHydrationWarning>
      <ambientLight intensity={0.5} />
      <group {...props} dispose={null}>
        <group position={[0, -3, 0]} scale={0.5}>
          <mesh
            geometry={nodes.Ch07_Heels.geometry}
            material={materials.Ch07_body}
          />
          <mesh
            geometry={nodes.Ch07_Body.geometry}
            material={materials.Ch07_body}
          />
          <mesh
            geometry={nodes.Ch07_Eyelashes.geometry}
            material={materials.Ch07_hair}
          />
          <mesh
            geometry={nodes.Ch07_Pants.geometry}
            material={materials.Ch07_body}
          />
          <mesh
            geometry={nodes.Ch07_Suit.geometry}
            material={materials.Ch07_body}
            meshName="Ch07_Suit"
          />
          <mesh
            geometry={nodes.Ch07_Shirt.geometry}
            material={materials.Ch07_body}
          />
          <mesh
            geometry={nodes.Ch07_Hair.geometry}
            material={materials.Ch07_hair}
          />
        </group>
      </group>
      <directionalLight position={[10, 10, 5]} intensity={1} />
      <directionalLight position={[-10, -10, -5]} intensity={1} />
      <pointLight position={[10, 10, 10]} intensity={0.5} />
      <pointLight position={[-10, -10, -10]} intensity={0.5} />
      <OrbitControls />
    </Canvas>
  );
}

useGLTF.preload("/Models/standingIdle.glb");
