-- Baseline schema for the My Butler Supabase project.
--
-- This repo had no supabase/migrations directory until this file was added,
-- so the actual table-creation migrations were never tracked - the schema
-- was built directly in the Supabase dashboard/SQL editor. This file is a
-- best-effort reconstruction from live introspection (list_tables, a full
-- pg_policies dump, and pg_get_functiondef on every function), captured
-- immediately before the fix migrations that follow it were applied, so
-- history in this repo matches what actually happened to the live database.
--
-- Known gaps: this does not attempt to capture secondary indexes beyond
-- what's implied by PRIMARY KEY/UNIQUE constraints, since those weren't part
-- of what was introspected. The `customers_insert_notify` trigger's exact
-- attachment (assumed AFTER INSERT ON public.customers below) was not
-- re-verified before this file was written - confirm against the live
-- project before treating it as authoritative.
--
-- This file is NOT meant to be re-run against the live project (the tables
-- already exist there) - it exists so the schema is reviewable by reading
-- the repo, and so a fresh environment could be bootstrapped from it.

-- ============================================================================
-- Tables
-- ============================================================================

create table public.customers (
  id uuid primary key default auth.uid(),
  first_name character varying not null,
  last_name character varying not null,
  email character varying not null unique,
  phone_no text,
  profile_picture text,
  display_name text not null,
  location text,
  supabase_user_id uuid not null unique,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  constraint users_supabase_user_id_fkey foreign key (supabase_user_id) references auth.users (id)
);
comment on table public.customers is 'This table stores essential customer profile information, such as name, email, address, and contact details. It is linked to the Supabase authentication system via the supabase_user_id column, which ensures that user records are tied to authenticated users.';

create table public.brands (
  id uuid primary key default auth.uid(),
  name character varying not null,
  description text not null,
  profile_picture text,
  url text unique,
  location text,
  contact text,
  email text not null unique,
  supabase_user_id uuid not null unique,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  constraint brands_supabase_user_id_fkey foreign key (supabase_user_id) references auth.users (id)
);
comment on table public.brands is 'This table stores information about fashion brands, including their name, description, logo image, and website URL. Each brand can have multiple associated lineups, allowing the application to display the brand''s offerings.';

create table public.categories (
  id integer primary key generated by default as identity,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
comment on table public.categories is 'This table categorizes products in the e-commerce section, like "T-Shirts," "Shoes," or "Accessories." It allows items to be grouped by their type for easy browsing by users.';

create table public.collections (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null default auth.uid(),
  name text not null,
  slug text not null,
  description text,
  display_image text,
  category_id integer,
  category text,
  created_at timestamptz default (now() at time zone 'utc'),
  updated_at timestamptz default (now() at time zone 'utc'),
  constraint lineups_brand_id_fkey foreign key (brand_id) references public.brands (id),
  constraint collections_category_id_fkey foreign key (category_id) references public.categories (id),
  constraint collections_category_fkey foreign key (category) references public.categories (name)
);
comment on table public.collections is 'The collections table stores various collections offered by brands, such as seasonal collections. It includes details about each collection''s name, description, display image, and the brand it belongs to. The table helps organize and display brand-specific offerings on your platform.';

create table public.products (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null default auth.uid(),
  collection_id uuid, -- intentionally not FK-constrained in the live schema
  category_id integer not null,
  name text not null,
  slug text not null unique,
  description text not null,
  price numeric not null,
  product_images text[],
  specifications jsonb not null,
  features text[] not null,
  stock_quantity integer not null default 0,
  rating numeric default 0 check (rating >= 0 and rating <= 5),
  reviews_count integer default 0,
  free_shipping boolean default false,
  warranty_years integer default 0,
  return_days integer default 0,
  created_at timestamptz,
  updated_at timestamptz,
  constraint products_brand_id_fkey foreign key (brand_id) references public.brands (id),
  constraint items_category_id_fkey foreign key (category_id) references public.categories (id)
);
comment on table public.products is 'The items table handles the e-commerce items listed on the platform. It stores comprehensive details for each product, including the name, price, description, images, sizes, and category. This table enables efficient product listing and retrieval for the e-commerce section of the app.';

create table public.events (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null default auth.uid(),
  title text not null,
  slug text not null unique,
  description text,
  start_date timestamp not null,
  end_date timestamp,
  location character varying,
  display_image text,
  tickets_url text,
  is_virtual boolean default false,
  capacity integer not null default 1 check (capacity > 0),
  speakers text default 'Undisclosed',
  duration_hours integer,
  exhibitor_count integer,
  admission_price numeric default 0,
  parking_available boolean default false,
  registration_basis text default 'First come, first served basis',
  featured_speakers_description text,
  what_to_expect text[] not null default '{}',
  created_at timestamptz,
  updated_at timestamptz,
  constraint events_brand_id_fkey foreign key (brand_id) references public.brands (id)
);
comment on table public.events is 'The events table stores information about upcoming fashion events, including the event title, description, start/end dates, location, and ticket purchasing links. This table provides users with details on fashion events they can attend, either virtually or physically.';
comment on column public.events.what_to_expect is 'Array of bullet points describing what attendees can expect';
comment on column public.events.duration_hours is 'Event duration in hours';
comment on column public.events.exhibitor_count is 'Number of exhibitors/vendors';
comment on column public.events.admission_price is 'Ticket price (0 for free events)';
comment on column public.events.parking_available is 'Whether parking is available on-site';
comment on column public.events.registration_basis is 'Registration policy description';
comment on column public.events.featured_speakers_description is 'Description of featured speakers or presenters';

create table public.news (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null default auth.uid(),
  title text not null,
  slug text not null unique,
  content text not null,
  description text,
  author character varying,
  author_bio text,
  display_image text,
  tags text[],
  reading_time_minutes integer default 5,
  created_at timestamptz,
  updated_at timestamptz,
  constraint news_brand_id_fkey foreign key (brand_id) references public.brands (id)
);
comment on table public.news is 'The news table stores articles, blogs, or updates related to the fashion industry. It includes details like the title, author, publication date, content, and associated tags. This helps you manage and display fashion-related news or blogs in your platform.';
comment on column public.news.reading_time_minutes is 'Estimated reading time in minutes';
comment on column public.news.author_bio is 'Author biography or description';

create table public.cart (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  item_id uuid,
  item_type text,
  quantity integer not null default 1,
  added_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp,
  constraint cart_user_id_fkey foreign key (user_id) references public.customers (id)
);
comment on table public.cart is 'This table tracks user carts by storing the list of items that a user has added. It helps manage the user''s shopping session and persists cart data until the purchase is complete.';

create table public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  target_type text not null,
  target_id uuid not null,
  created_at timestamptz,
  constraint bookmarks_user_id_fkey foreign key (user_id) references public.customers (id)
);

create table public.reviews (
  id integer primary key generated by default as identity,
  user_id uuid not null default auth.uid(),
  rating numeric check (rating >= 0 and rating <= 5),
  review_text text,
  created_at timestamp default now(),
  constraint reviews_user_id_fkey foreign key (user_id) references public.customers (id)
);
comment on table public.reviews is 'The reviews table stores user-submitted ratings and reviews for products listed in the items table. It allows users to share their feedback on products and helps other users make informed purchase decisions.';

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  type character varying not null,
  title character varying not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp default now(),
  constraint notifications_user_id_fkey foreign key (user_id) references public.customers (id)
);

create table public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  title text not null default 'New Chat',
  messages jsonb[] not null,
  created_at timestamptz not null unique default now(),
  constraint chats_user_id_fkey foreign key (user_id) references public.customers (id)
);
comment on table public.chats is 'All user chats with the Butler AI';

create table public.camera_pictures (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  image_url text not null default '',
  full_path text not null default '',
  path text not null default '',
  created_at timestamptz not null default now(),
  constraint camera_pictures_user_id_fkey foreign key (user_id) references public.customers (id),
  constraint camera_pictures_id_fkey foreign key (id) references storage.objects (id)
);

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.customers enable row level security;
alter table public.brands enable row level security;
alter table public.categories enable row level security;
alter table public.collections enable row level security;
alter table public.products enable row level security;
alter table public.events enable row level security;
alter table public.news enable row level security;
alter table public.cart enable row level security;
alter table public.bookmarks enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;
alter table public.chats enable row level security;
alter table public.camera_pictures enable row level security;

-- Policies as they existed before this repo's fix migrations (below) tightened
-- them - reproduced here so the fix migrations' DROP POLICY IF EXISTS targets
-- resolve to something real when read in order, and so the "before" state is
-- reviewable rather than only described in commit messages.

create policy "Enable insert for authenticated users only" on public.bookmarks for insert to authenticated with check (true);
create policy "Enable users to view their own data only" on public.bookmarks for select to authenticated using (auth.uid() = user_id);

create policy "Enable insert for authenticated users only" on public.brands for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.brands for select to public using (true);

create policy "Enable insert for authenticated users only" on public.camera_pictures for insert to authenticated with check (true);
create policy "Enable users to view their own data only" on public.camera_pictures for select to authenticated using (auth.uid() = user_id);

create policy "Enable insert for authenticated users only" on public.cart for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on public.cart for select to authenticated using (true);

create policy "Enable insert for authenticated users only" on public.categories for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.categories for select to public using (true);

create policy "Enable delete for users based on user_id" on public.chats for delete to public using (auth.uid() = user_id);
create policy "Enable insert for authenticated users only" on public.chats for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on public.chats for select to authenticated using (true);
create policy "Enable update for authenticated users" on public.chats for update to authenticated using (true);

create policy "Enable insert for authenticated users only" on public.collections for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.collections for select to public using (true);

create policy "Enable insert for all users" on public.customers for insert to public with check (true);
create policy "Enable read access for all users" on public.customers for select to authenticated using (true);

create policy "Enable insert for authenticated users only" on public.events for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.events for select to public using (true);

create policy "Enable insert for authenticated users only" on public.news for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.news for select to public using (true);

create policy "Enable insert for authenticated users only" on public.notifications for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.notifications for select to public using (true);

create policy "Enable insert for authenticated users only" on public.products for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.products for select to public using (true);

create policy "Enable insert for authenticated users only" on public.reviews for insert to authenticated with check (true);
create policy "Enable read access for all users" on public.reviews for select to public using (true);

-- ============================================================================
-- Functions and triggers
-- ============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $function$
declare
    full_name text;
    split_name text[];
    user_role_id int;
    brand_name text;
    brand_description text;
    brand_url text;
begin
    user_role_id := (new.raw_user_meta_data->>'role_id')::int;

    if user_role_id = 4 then
        brand_name := new.raw_user_meta_data->>'brand_name';
        brand_description := new.raw_user_meta_data->>'brand_description';
        brand_url := new.raw_user_meta_data->>'brand_url';

        if brand_name is null or brand_name = '' then
            raise exception 'Brand name is required for user ID: %', new.id;
        end if;

        if brand_description is null or brand_description = '' then
            raise exception 'Brand description is required for user ID: %', new.id;
        end if;

        if brand_url is null or brand_url = '' then
            raise exception 'Brand URL is required for user ID: %', new.id;
        end if;

        -- BUG, fixed in 20260729172615_fix_handle_new_user_contact_column_and_search_path.sql:
        -- `contact_no` does not exist on public.brands (the column is `contact`),
        -- so this insert throws and every brand signup rolls back.
        insert into public.brands (
            id, name, description, url, email, contact_no, location, supabase_user_id
        ) values (
            new.id,
            brand_name,
            brand_description,
            brand_url,
            new.email,
            new.phone,
            new.raw_user_meta_data->>'brand_location',
            new.id
        );
    else
        full_name := new.raw_user_meta_data->>'full_name';

        if full_name is null or full_name = '' then
            raise exception 'Full name is missing or empty for user ID: %', new.id;
        end if;

        split_name := string_to_array(full_name, ' ');

        if array_length(split_name, 1) is null or array_length(split_name, 1) = 0 then
            raise exception 'Full name could not be split for user ID: %', new.id;
        end if;

        insert into public.customers (
            id, email, display_name, first_name, last_name, profile_picture, phone_no, supabase_user_id
        ) values (
            new.id,
            new.email,
            full_name,
            split_name[1],
            coalesce(array_to_string(split_name[2:], ' '), ''),
            new.raw_user_meta_data->>'picture',
            new.phone,
            new.id
        );
    end if;

    return new;
exception when others then
    raise exception 'Error in handle_new_user trigger for user ID %: %', new.id, sqlerrm;
end;
$function$;

create trigger on_auth_user_signup after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.customers_insert_notify()
returns trigger
language plpgsql
security definer
as $function$begin
  insert into public.notifications (user_id, type, title, message, created_at)
  values (new.id, 'welcome', 'Welcome to our community', 'Hi %s! Welcome to our platform — we are excited to have you. You can visit your profile to get started there.', now());
  return new;
end;$function$;

-- Assumed attachment (not re-verified against the live project - see header note).
create trigger customers_insert_notify after insert on public.customers for each row execute function public.customers_insert_notify();

create or replace function public.toggle_bookmark(_target_id uuid, _target_type text)
returns text
language plpgsql
security definer
as $function$
declare
  existing_bookmark bookmarks%rowtype;
begin
  if auth.uid() is null then
    raise exception 'User must be authenticated';
  end if;

  -- BUG, fixed in 20260729172653_fix_toggle_bookmark_wrong_table_and_search_path.sql:
  -- operates on `cart`, which has no target_id/target_type columns, instead
  -- of `bookmarks` - every call throws "column target_id does not exist".
  select * into existing_bookmark
  from cart
  where user_id = auth.uid()
    and target_id = _target_id;

  if found then
    delete from cart
    where user_id = auth.uid()
      and target_id = _target_id;
    return 'removed';
  else
    insert into cart (user_id, target_id, target_type)
    values (auth.uid(), _target_id, _target_type);
    return 'added';
  end if;

exception
  when others then
    raise exception 'Error toggling bookmark: %', sqlerrm;
end;
$function$;

create or replace function public.toggle_cart(_item_id uuid, _quantity integer, _item_type text)
returns text
language plpgsql
security definer
as $function$
declare
  existing_cart_item cart%rowtype;
begin
  if auth.uid() is null then
    raise exception 'User must be authenticated';
  end if;

  select * into existing_cart_item
  from cart
  where user_id = auth.uid()
    and item_id = _item_id;

  if found then
    delete from cart
    where user_id = auth.uid()
      and item_id = _item_id;
    return 'removed';
  else
    insert into cart (user_id, item_id, item_type, quantity)
    values (auth.uid(), _item_id, _item_type, _quantity);
    return 'added';
  end if;

exception
  when others then
    raise exception 'Error toggling cart: %', sqlerrm;
end;
$function$;

-- BUG, fixed in 20260729172633_add_ownership_checks_to_profile_update_rpcs.sql:
-- neither function below checks that the caller (auth.uid()) is actually
-- _supabase_user_id, and both are callable by the anon role - an
-- unauthenticated way to overwrite any customer's or brand's profile.

create or replace function public.update_customer_details(
  _supabase_user_id uuid, _display_name text, _profile_picture text, _email text, _location text
)
returns void
language plpgsql
security definer
as $function$
begin
  begin
    update auth.users
    set raw_user_meta_data = jsonb_set(
      raw_user_meta_data,
      '{display_name}',
      to_jsonb(_display_name),
      true
    )
    where id = _supabase_user_id;

    update customers
    set
      display_name = _display_name,
      profile_picture = _profile_picture,
      email = _email,
      location = _location
    where supabase_user_id = _supabase_user_id;
  end;
end;
$function$;

create or replace function public.update_brand_details(
  _supabase_user_id uuid, _name text, _email text, _location text, _description text,
  _url text, _profile_picture text, _contact text
)
returns void
language plpgsql
security definer
as $function$
begin
  begin
    update auth.users
    set raw_user_meta_data = jsonb_set(
      raw_user_meta_data,
      '{display_name}',
      to_jsonb(_name),
      true
    )
    where id = _supabase_user_id;

    update brands
    set
      name = _name,
      email = _email,
      location = _location,
      description = _description,
      url = _url,
      profile_picture = _profile_picture,
      contact = _contact
    where supabase_user_id = _supabase_user_id;
  end;
end;
$function$;
